baseURL = 'https://w0r.mx/'
languageCode = 'en-us'
title = 'Field Reports from W0RMX'
themesDir = "./themes/"
theme = "hugo-split-gallery"

[taxonomies]
  location = "locations"
  season = "seasons"

[params]
  subtitle = 'Field Reports from W0RMX'
  DefaultContentLanguage = "en"

  robots = "index, follow"
  favicon = "./static/favicon.ico"
  footnote = """
  <ul class='list-inline'>
    <li class='list-inline-item me-4'><a href='https://www.qrz.com/db/w0rmx'><i class='fa fa-globe fa-fw'></i>QRZ</a></li>
    <li class='list-inline-item me-4'><a href='https://pota.app/#/profile/W0RMX'><i class='fa fa-globe fa-fw'></i>POTA</a></li>
    <li class='list-inline-item me-4'><a href='https://sotl.as/activators/W0RMX'><i class='fa fa-map fa-fw'></i>SOTA</a></li>
  </ul>
  """
  # description = "description"
  #images = ["DSCF0348.jpg"]
  # customCss = ['css/custom1.css', 'css/custom2.css']
  # customJs = ['js/custom1.js', 'js/custom2.js']
  # enableDownloadAll = false
  #footnote = "Foo bar"
  includeOriginalImage = true
  # largeImageSize = "2000x"
  # siteLogo = ""
  # useDefaultColors = true
  # useDefaultFonts = true
  # galleryLoop = true
  # galleryCounter = true
  # galleryButtons = ["zoom", "slideShow", "close"]
  # galleryAnimationEffect = "zoom"
  # galleryAnimationDuration = 366
  # galleryTransitionEffect = "fade"
  # galleryTransitionDuration = 366
  # gallerySlideshowSpeed = 3000
  # sharedMediaBundle = "/media"
  # showTranslations = true
  map2gpx = false
  paginate = 10
  # columns = 2
  # columnsMinItems = 10

  [params.taxonomies]
    [params.taxonomies.locations]
      icon = "location-arrow"
    [params.taxonomies.seasons]
      icon = "calendar"
